Repository trailofbits/algo, pull requests merged in 2019-03, with the labels that each got.

#1334 Refactoring
  README.md
  config.cfg
  input.yml
  playbooks/cloud-post.yml
  playbooks/win_script_rebuild.yml
  roles/client/tasks/main.yml
  roles/common/handlers/main.yml
  roles/common/tasks/freebsd.yml
  roles/common/tasks/iptables.yml
  roles/common/tasks/ubuntu.yml
  roles/common/templates/rules.v4.j2
  roles/common/templates/rules.v6.j2
  roles/ssh_tunneling/defaults/main.yml
  roles/ssh_tunneling/tasks/main.yml
  roles/ssh_tunneling/templates/known_hosts.j2
  roles/strongswan/defaults/main.yml
  roles/strongswan/handlers/main.yml
  roles/strongswan/meta/main.yml
  roles/strongswan/tasks/client_configs.yml
  roles/strongswan/tasks/distribute_keys.yml
  roles/strongswan/tasks/ipsec_configuration.yml
  roles/strongswan/tasks/main.yml
  roles/strongswan/tasks/openssl.yml
  roles/strongswan/tasks/ubuntu.yml
  roles/strongswan/templates/100-CustomLimitations.conf.j2
  roles/strongswan/templates/client_ipsec.conf.j2
  roles/strongswan/templates/client_ipsec.secrets.j2
  roles/strongswan/templates/client_windows.ps1.j2
  roles/strongswan/templates/ipsec.conf.j2
  roles/strongswan/templates/ipsec.secrets.j2
  roles/strongswan/templates/mobileconfig.j2
  roles/strongswan/templates/openssl.cnf.j2
  roles/strongswan/templates/strongswan.conf.j2
  roles/vpn/tasks/distribute_keys.yml
  roles/wireguard/defaults/main.yml
  roles/wireguard/tasks/keys.yml
  roles/wireguard/tasks/main.yml
  roles/wireguard/templates/client.conf.j2
  roles/wireguard/templates/server.conf.j2
  server.yml
  tests/update-users.sh
  users.yml
Labels: ready_to_merge

#1033 Simplify Apple Profile Configuration Template
  roles/strongswan/templates/mobileconfig.j2
Labels: 1.1, needs_rebase

#1366 Script to support cloud-init and local easy deploy
  .travis.yml
  docs/deploy-from-script-or-cloud-init-to-localhost.md
  install.sh
  tests/cloud-init.sh
Labels: 1.1, deploy_enhancements
