Repository trailofbits/algo, pull requests merged in 2019-05, with the labels that each got.

#1415 Facts definition fix
  input.yml
  playbooks/cloud-pre.yml
  roles/local/tasks/prompts.yml
  users.yml
Labels: ready_to_merge

#1410 Scaleway modules
  docs/deploy-from-ansible.md
  library/scaleway_compute.py
  roles/cloud-scaleway/tasks/image_facts.yml
  roles/cloud-scaleway/tasks/main.yml
  roles/cloud-scaleway/tasks/prompts.yml
Labels: 1.1

#1429 Randomly generated IP address for the local dns resolver
  config.cfg
  docs/client-linux-wireguard.md
  docs/faq.md
  main.yml
  requirements.txt
  roles/common/handlers/main.yml
  roles/common/tasks/freebsd.yml
  roles/common/templates/10-algo-lo100.network.j2
  roles/common/templates/rules.v6.j2
  roles/dns_adblocking/templates/dnsmasq.conf.j2
  roles/wireguard/defaults/main.yml
  roles/wireguard/templates/server.conf.j2
  tests/cloud-init.sh
  tests/ipsec-client.sh
  tests/local-deploy.sh
  tests/update-users.sh
  tests/wireguard-client.sh
Labels: ready_to_merge

#1381 fix: Use Ansible’s wait_for_connection to avoid SSH connection failure after initial post-update Ubuntu reboot
  roles/common/tasks/ubuntu.yml
Labels: needs_changes

#1292 AWS support for existing EIP (revised)
  config.cfg
  roles/cloud-ec2/defaults/main.yml
  roles/cloud-ec2/files/stack.yaml
  roles/cloud-ec2/tasks/cloudformation.yml
  roles/cloud-ec2/tasks/prompts.yml
Labels: 1.1, needs_tests

#1405 Support for Ubuntu 19.04
  .travis.yml
  README.md
  config.cfg
  docs/cloud-do.md
  docs/deploy-to-ubuntu.md
  docs/deploy-to-unsupported-cloud.md
  docs/index.md
  input.yml
  roles/dns_encryption/files/apparmor.profile.dnscrypt-proxy
  roles/dns_encryption/tasks/ubuntu.yml
  roles/strongswan/tasks/ubuntu.yml
  tests/pre-deploy.sh
Labels: 1.1
